export type CarModelOption = { make: string; model: string; segment: string; label: string };

export const CAR_MODEL_OPTIONS: CarModelOption[] = [
  {
    make: 'Maruti Suzuki',
    model: 'Alto K10',
    segment: 'Hatchback',
    label: 'Maruti Suzuki · Alto K10 · Hatchback',
  },
  {
    make: 'Maruti Suzuki',
    model: 'S-Presso',
    segment: 'Hatchback',
    label: 'Maruti Suzuki · S-Presso · Hatchback',
  },
  {
    make: 'Maruti Suzuki',
    model: 'WagonR',
    segment: 'Hatchback',
    label: 'Maruti Suzuki · WagonR · Hatchback',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Celerio',
    segment: 'Hatchback',
    label: 'Maruti Suzuki · Celerio · Hatchback',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Swift',
    segment: 'Hatchback',
    label: 'Maruti Suzuki · Swift · Hatchback',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Baleno',
    segment: 'Hatchback',
    label: 'Maruti Suzuki · Baleno · Hatchback',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Ignis',
    segment: 'Hatchback',
    label: 'Maruti Suzuki · Ignis · Hatchback',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Dzire',
    segment: 'Sedan',
    label: 'Maruti Suzuki · Dzire · Sedan',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Ciaz',
    segment: 'Sedan',
    label: 'Maruti Suzuki · Ciaz · Sedan',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Brezza',
    segment: 'SUV',
    label: 'Maruti Suzuki · Brezza · SUV',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Fronx',
    segment: 'SUV',
    label: 'Maruti Suzuki · Fronx · SUV',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Grand Vitara',
    segment: 'SUV',
    label: 'Maruti Suzuki · Grand Vitara · SUV',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Ertiga',
    segment: 'MPV',
    label: 'Maruti Suzuki · Ertiga · MPV',
  },
  {
    make: 'Maruti Suzuki',
    model: 'XL6',
    segment: 'MPV',
    label: 'Maruti Suzuki · XL6 · MPV',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Invicto',
    segment: 'MPV',
    label: 'Maruti Suzuki · Invicto · MPV',
  },
  {
    make: 'Hyundai',
    model: 'Grand i10 Nios',
    segment: 'Hatchback',
    label: 'Hyundai · Grand i10 Nios · Hatchback',
  },
  {
    make: 'Hyundai',
    model: 'i20',
    segment: 'Hatchback',
    label: 'Hyundai · i20 · Hatchback',
  },
  {
    make: 'Hyundai',
    model: 'i20 N Line',
    segment: 'Hatchback',
    label: 'Hyundai · i20 N Line · Hatchback',
  },
  {
    make: 'Hyundai',
    model: 'Aura',
    segment: 'Sedan',
    label: 'Hyundai · Aura · Sedan',
  },
  {
    make: 'Hyundai',
    model: 'Verna',
    segment: 'Sedan',
    label: 'Hyundai · Verna · Sedan',
  },
  {
    make: 'Hyundai',
    model: 'Exter',
    segment: 'SUV',
    label: 'Hyundai · Exter · SUV',
  },
  {
    make: 'Hyundai',
    model: 'Venue',
    segment: 'SUV',
    label: 'Hyundai · Venue · SUV',
  },
  {
    make: 'Hyundai',
    model: 'Venue N Line',
    segment: 'SUV',
    label: 'Hyundai · Venue N Line · SUV',
  },
  {
    make: 'Hyundai',
    model: 'Creta',
    segment: 'SUV',
    label: 'Hyundai · Creta · SUV',
  },
  {
    make: 'Hyundai',
    model: 'Creta N Line',
    segment: 'SUV',
    label: 'Hyundai · Creta N Line · SUV',
  },
  {
    make: 'Hyundai',
    model: 'Alcazar',
    segment: 'SUV',
    label: 'Hyundai · Alcazar · SUV',
  },
  {
    make: 'Hyundai',
    model: 'Tucson',
    segment: 'SUV',
    label: 'Hyundai · Tucson · SUV',
  },
  {
    make: 'Tata',
    model: 'Tiago',
    segment: 'Hatchback',
    label: 'Tata · Tiago · Hatchback',
  },
  {
    make: 'Tata',
    model: 'Tigor',
    segment: 'Sedan',
    label: 'Tata · Tigor · Sedan',
  },
  {
    make: 'Tata',
    model: 'Altroz',
    segment: 'Hatchback',
    label: 'Tata · Altroz · Hatchback',
  },
  {
    make: 'Tata',
    model: 'Punch',
    segment: 'SUV',
    label: 'Tata · Punch · SUV',
  },
  {
    make: 'Tata',
    model: 'Nexon',
    segment: 'SUV',
    label: 'Tata · Nexon · SUV',
  },
  {
    make: 'Tata',
    model: 'Nexon EV',
    segment: 'EV',
    label: 'Tata · Nexon EV · EV',
  },
  {
    make: 'Tata',
    model: 'Harrier',
    segment: 'SUV',
    label: 'Tata · Harrier · SUV',
  },
  {
    make: 'Tata',
    model: 'Safari',
    segment: 'SUV',
    label: 'Tata · Safari · SUV',
  },
  {
    make: 'Mahindra',
    model: 'Bolero',
    segment: 'SUV',
    label: 'Mahindra · Bolero · SUV',
  },
  {
    make: 'Mahindra',
    model: 'Bolero Neo',
    segment: 'SUV',
    label: 'Mahindra · Bolero Neo · SUV',
  },
  {
    make: 'Mahindra',
    model: 'Thar',
    segment: 'SUV',
    label: 'Mahindra · Thar · SUV',
  },
  {
    make: 'Mahindra',
    model: 'Thar Roxx',
    segment: 'SUV',
    label: 'Mahindra · Thar Roxx · SUV',
  },
  {
    make: 'Mahindra',
    model: 'Scorpio Classic',
    segment: 'SUV',
    label: 'Mahindra · Scorpio Classic · SUV',
  },
  {
    make: 'Mahindra',
    model: 'Scorpio N',
    segment: 'SUV',
    label: 'Mahindra · Scorpio N · SUV',
  },
  {
    make: 'Mahindra',
    model: 'XUV300',
    segment: 'SUV',
    label: 'Mahindra · XUV300 · SUV',
  },
  {
    make: 'Mahindra',
    model: 'XUV400',
    segment: 'EV',
    label: 'Mahindra · XUV400 · EV',
  },
  {
    make: 'Mahindra',
    model: 'XUV700',
    segment: 'SUV',
    label: 'Mahindra · XUV700 · SUV',
  },
  {
    make: 'Kia',
    model: 'Sonet',
    segment: 'SUV',
    label: 'Kia · Sonet · SUV',
  },
  {
    make: 'Kia',
    model: 'Seltos',
    segment: 'SUV',
    label: 'Kia · Seltos · SUV',
  },
  {
    make: 'Kia',
    model: 'Carens',
    segment: 'MPV',
    label: 'Kia · Carens · MPV',
  },
  {
    make: 'Kia',
    model: 'EV6',
    segment: 'EV',
    label: 'Kia · EV6 · EV',
  },
  {
    make: 'Toyota',
    model: 'Glanza',
    segment: 'Hatchback',
    label: 'Toyota · Glanza · Hatchback',
  },
  {
    make: 'Toyota',
    model: 'Urban Cruiser Taisor',
    segment: 'SUV',
    label: 'Toyota · Urban Cruiser Taisor · SUV',
  },
  {
    make: 'Toyota',
    model: 'Hyryder',
    segment: 'SUV',
    label: 'Toyota · Hyryder · SUV',
  },
  {
    make: 'Toyota',
    model: 'Innova Crysta',
    segment: 'MPV',
    label: 'Toyota · Innova Crysta · MPV',
  },
  {
    make: 'Toyota',
    model: 'Innova Hycross',
    segment: 'MPV',
    label: 'Toyota · Innova Hycross · MPV',
  },
  {
    make: 'Toyota',
    model: 'Fortuner',
    segment: 'SUV',
    label: 'Toyota · Fortuner · SUV',
  },
  {
    make: 'Toyota',
    model: 'Fortuner Legender',
    segment: 'SUV',
    label: 'Toyota · Fortuner Legender · SUV',
  },
  {
    make: 'Toyota',
    model: 'Camry',
    segment: 'Sedan',
    label: 'Toyota · Camry · Sedan',
  },
  {
    make: 'Toyota',
    model: 'Vellfire',
    segment: 'Luxury MPV',
    label: 'Toyota · Vellfire · Luxury MPV',
  },
  {
    make: 'Skoda',
    model: 'Slavia',
    segment: 'Sedan',
    label: 'Skoda · Slavia · Sedan',
  },
  {
    make: 'Skoda',
    model: 'Kushaq',
    segment: 'SUV',
    label: 'Skoda · Kushaq · SUV',
  },
  {
    make: 'Skoda',
    model: 'Kodiaq',
    segment: 'SUV',
    label: 'Skoda · Kodiaq · SUV',
  },
  {
    make: 'Skoda',
    model: 'Superb',
    segment: 'Sedan',
    label: 'Skoda · Superb · Sedan',
  },
  {
    make: 'Volkswagen',
    model: 'Virtus',
    segment: 'Sedan',
    label: 'Volkswagen · Virtus · Sedan',
  },
  {
    make: 'Volkswagen',
    model: 'Taigun',
    segment: 'SUV',
    label: 'Volkswagen · Taigun · SUV',
  },
  {
    make: 'Volkswagen',
    model: 'Tiguan',
    segment: 'SUV',
    label: 'Volkswagen · Tiguan · SUV',
  },
  {
    make: 'MG',
    model: 'Comet EV',
    segment: 'EV',
    label: 'MG · Comet EV · EV',
  },
  {
    make: 'MG',
    model: 'Astor',
    segment: 'SUV',
    label: 'MG · Astor · SUV',
  },
  {
    make: 'MG',
    model: 'Hector',
    segment: 'SUV',
    label: 'MG · Hector · SUV',
  },
  {
    make: 'MG',
    model: 'Hector Plus',
    segment: 'SUV',
    label: 'MG · Hector Plus · SUV',
  },
  {
    make: 'MG',
    model: 'Gloster',
    segment: 'SUV',
    label: 'MG · Gloster · SUV',
  },
  {
    make: 'MG',
    model: 'ZS EV',
    segment: 'EV',
    label: 'MG · ZS EV · EV',
  },
  {
    make: 'Jeep',
    model: 'Compass',
    segment: 'SUV',
    label: 'Jeep · Compass · SUV',
  },
  {
    make: 'Jeep',
    model: 'Meridian',
    segment: 'SUV',
    label: 'Jeep · Meridian · SUV',
  },
  {
    make: 'Mercedes',
    model: 'A-Class',
    segment: 'Hatchback',
    label: 'Mercedes · A-Class · Hatchback',
  },
  {
    make: 'Mercedes',
    model: 'C-Class',
    segment: 'Sedan',
    label: 'Mercedes · C-Class · Sedan',
  },
  {
    make: 'Mercedes',
    model: 'E-Class',
    segment: 'Sedan',
    label: 'Mercedes · E-Class · Sedan',
  },
  {
    make: 'Mercedes',
    model: 'S-Class',
    segment: 'Sedan',
    label: 'Mercedes · S-Class · Sedan',
  },
  {
    make: 'Mercedes',
    model: 'GLA',
    segment: 'SUV',
    label: 'Mercedes · GLA · SUV',
  },
  {
    make: 'Mercedes',
    model: 'GLC',
    segment: 'SUV',
    label: 'Mercedes · GLC · SUV',
  },
  {
    make: 'Mercedes',
    model: 'GLE',
    segment: 'SUV',
    label: 'Mercedes · GLE · SUV',
  },
  {
    make: 'Mercedes',
    model: 'GLS',
    segment: 'SUV',
    label: 'Mercedes · GLS · SUV',
  },
  {
    make: 'BMW',
    model: '2 Series',
    segment: 'Sedan',
    label: 'BMW · 2 Series · Sedan',
  },
  {
    make: 'BMW',
    model: '3 Series',
    segment: 'Sedan',
    label: 'BMW · 3 Series · Sedan',
  },
  {
    make: 'BMW',
    model: '5 Series',
    segment: 'Sedan',
    label: 'BMW · 5 Series · Sedan',
  },
  {
    make: 'BMW',
    model: '7 Series',
    segment: 'Sedan',
    label: 'BMW · 7 Series · Sedan',
  },
  {
    make: 'BMW',
    model: 'X1',
    segment: 'SUV',
    label: 'BMW · X1 · SUV',
  },
  {
    make: 'BMW',
    model: 'X3',
    segment: 'SUV',
    label: 'BMW · X3 · SUV',
  },
  {
    make: 'BMW',
    model: 'X5',
    segment: 'SUV',
    label: 'BMW · X5 · SUV',
  },
  {
    make: 'BMW',
    model: 'X7',
    segment: 'SUV',
    label: 'BMW · X7 · SUV',
  },
  {
    make: 'Audi',
    model: 'A4',
    segment: 'Sedan',
    label: 'Audi · A4 · Sedan',
  },
  {
    make: 'Audi',
    model: 'A6',
    segment: 'Sedan',
    label: 'Audi · A6 · Sedan',
  },
  {
    make: 'Audi',
    model: 'Q3',
    segment: 'SUV',
    label: 'Audi · Q3 · SUV',
  },
  {
    make: 'Audi',
    model: 'Q5',
    segment: 'SUV',
    label: 'Audi · Q5 · SUV',
  },
  {
    make: 'Audi',
    model: 'Q7',
    segment: 'SUV',
    label: 'Audi · Q7 · SUV',
  },
];

export const CAR_MODELS_BY_MAKE = CAR_MODEL_OPTIONS.reduce<Record<string, CarModelOption[]>>((acc, option) => {
  const key = option.make.trim() || 'Other';
  if (!acc[key]) acc[key] = [];
  acc[key].push(option);
  return acc;
}, {});
